/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as PrivateLayoutRouteImport } from './../routes/_private/layout'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as PrivateProductsRouteImport } from './../routes/_private/products'
import { Route as PrivateDashboardRouteImport } from './../routes/_private/dashboard'
import { Route as PrivateAdministratorsRouteImport } from './../routes/_private/administrators'
import { Route as PrivateCategoriesIndexRouteImport } from './../routes/_private/categories/index'

const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateProductsRoute = PrivateProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateAdministratorsRoute = PrivateAdministratorsRouteImport.update({
  id: '/administrators',
  path: '/administrators',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateCategoriesIndexRoute = PrivateCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrators': typeof PrivateAdministratorsRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/products': typeof PrivateProductsRoute
  '/categories': typeof PrivateCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrators': typeof PrivateAdministratorsRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/products': typeof PrivateProductsRoute
  '/categories': typeof PrivateCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_private/administrators': typeof PrivateAdministratorsRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/products': typeof PrivateProductsRoute
  '/_private/categories/': typeof PrivateCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrators'
    | '/dashboard'
    | '/products'
    | '/categories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/administrators' | '/dashboard' | '/products' | '/categories'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_private/administrators'
    | '/_private/dashboard'
    | '/_private/products'
    | '/_private/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/products': {
      id: '/_private/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PrivateProductsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/administrators': {
      id: '/_private/administrators'
      path: '/administrators'
      fullPath: '/administrators'
      preLoaderRoute: typeof PrivateAdministratorsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/categories/': {
      id: '/_private/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PrivateCategoriesIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateAdministratorsRoute: typeof PrivateAdministratorsRoute
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateProductsRoute: typeof PrivateProductsRoute
  PrivateCategoriesIndexRoute: typeof PrivateCategoriesIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateAdministratorsRoute: PrivateAdministratorsRoute,
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateProductsRoute: PrivateProductsRoute,
  PrivateCategoriesIndexRoute: PrivateCategoriesIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
